url: "http://ninaelmer.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Nina Elmer" # the name of your site, e.g. ACME Corp.
description: " AI Fellow"
organization: "Infosys - Cambridge AI Center, DAMTP, University of Cambridge"
